extends SceneTree
const App = preload("res://scripts/app.gd")
const Motion = preload("res://scripts/device_motion.gd")
var app: Node2D
var checks := 0
var failures: Array[String] = []
func _initialize() -> void: call_deferred("run")
func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok:
		failures.append(message)
		printerr("FAIL " + message)
func ticks(n: int) -> void:
	for i in n: await physics_frame
	await process_frame
func touch(p: Vector2, pressed: bool) -> void:
	var event := InputEventScreenTouch.new()
	event.position = p
	event.pressed = pressed
	root.push_input(event, true)
func run() -> void:
	app = App.new()
	root.add_child(app)
	await ticks(3)
	var world = app.world
	check(world.ball_count() == 1 and world.springs.size() == 1, "fresh start is a ready-to-touch spring toy")
	check(world.bounds.position.y == 76, "top decorative region is playable")
	world.clear()
	world.set_paused(true)
	var ball = world.spawn("ball", Vector2(210, 390))
	await ticks(3)
	var original_bounds: Rect2 = world.bounds
	var original_position: Vector2 = ball.position
	app.action("tray")
	await ticks(2)
	check(world.bounds == original_bounds and ball.position == original_position, "tray changes view only")
	app.action("tray")
	await ticks(2)
	touch(app.world_to_screen(ball.position), true)
	touch(app.world_to_screen(ball.position), false)
	await ticks(2)
	check(app.modal == "" and not app.hud.buttons.has("properties") and not app.hud.buttons.has("duplicate"), "tap has no floating actions")
	touch(app.world_to_screen(ball.position), true)
	await ticks(34)
	check(app.modal == "properties", "stationary long press opens sheet")
	await ticks(2)
	check(app.hud.sheet_rect.size.y <= 250 and app.hud.sliders.size() == 1, "compact one-slider sheet")
	check(app.world_to_screen(world.bounds.end).y < app.hud.sheet_rect.position.y, "whole world remains above sheet")
	check(ball.position == original_position and world.bounds == original_bounds, "editor never relocates bodies")
	var before_count: int = app.history.size()
	app.action("tab:1")
	await ticks(2)
	var slider: Rect2 = app.hud.sliders.mass.rect
	touch(Vector2(slider.end.x - 1, slider.get_center().y), true)
	touch(Vector2(slider.end.x - 1, slider.get_center().y), false)
	check(is_equal_approx(ball.mass, 5), "touch slider changes physical mass live")
	app.draft_set("mass", 2.5)
	app.close_editor(true)
	check(app.history.size() == before_count + 1, "edit session is one undo")
	app.action("undo")
	ball = world.bodies.values()[0]
	check(is_equal_approx(ball.mass, 1), "undo restores original mass")
	world.select(ball.uid)
	app.open_editor()
	app.draft_set("radius", 25)
	check(ball.props.radius == 25, "radius updates actual collider live")
	app.close_editor(false)
	ball = world.bodies.values()[0]
	check(ball.props.radius == 17 and ball.position == original_position, "restore returns full session snapshot")
	world.spawn("ball", ball.position + Vector2(38, 0))
	await ticks(3)
	world.select(ball.uid)
	app.open_editor()
	app.draft_set("radius", 30)
	check(ball.props.radius == 17 and app.edit_error != "", "overlapping growth rejected without teleport")
	app.close_editor(true)
	await ticks(2)
	app.hud.pointer_down(app.world_to_screen(ball.position), 0)
	app.hud.pointer_move(app.world_to_screen(ball.position + Vector2(55, -60)))
	await ticks(40)
	check(app.modal == "", "holding still after dragging never opens editor")
	app.hud.pointer_up(app.world_to_screen(ball.position))
	world.clear()
	var fan = world.spawn("fan", Vector2(220, 500))
	world.select(fan.uid)
	app.open_editor()
	app.draft_set("angle", 65)
	app.draft_set("strength", 2300)
	check(absf(rad_to_deg(fan.rotation) - 65) < 0.01 and fan.props.strength == 2300, "direction and strength apply live")
	app.action("duplicate")
	check(world.bodies.size() == 2 and app.modal == "", "secondary duplicate works")
	app.feedback.sound = true
	app.feedback.play("place")
	app.feedback.update_airflow(2400, 1)
	check(not app.feedback.airflow.playing, "fan is silent")
	var voices_silent := true
	for voice in app.feedback.voices: voices_silent = voices_silent and not voice.playing
	check(voices_silent, "UI/placement does not produce generic sound")
	check(app.feedback.streams.impact_metal.data != app.feedback.streams.impact_wood.data, "material waveforms differ")
	var motion := Motion.new()
	var g := Vector3(0, -9.8, 0)
	var response: Dictionary = motion.sample(g, g, 1.0 / 60)
	check(response.acceleration == Vector2.ZERO, "first sensor sample calibrates")
	for i in 100:
		response = motion.sample(Vector3(0.1, -9.8, 0), g, 1.0 / 60)
	check(response.acceleration == Vector2.ZERO, "sensor deadzone suppresses jitter")
	for i in 120:
		response = motion.sample(Vector3(8, -3, 0), Vector3(8, -3, 0), 1.0 / 60)
		check(response.acceleration.length() <= 120.01, "tilt capped")
	check(response.acceleration.x > 0, "tilt creates directional acceleration")
	response = motion.sample(g, Vector3(100, -9.8, 0), 1.0 / 60)
	check(response.impulse.length() <= 45.01 and response.impulse.length() > 0, "shake capped")
	response = motion.sample(g, Vector3(100, -9.8, 0), 1.0 / 60)
	check(response.impulse == Vector2.ZERO, "shake cooldown")
	response = motion.sample(g, Vector3(100, 0, 0), 1.0 / 60, true)
	check(response.acceleration == Vector2.ZERO and response.impulse == Vector2.ZERO, "edit and drag suppress sensors")
	response = motion.sample(g, g, 1.0 / 60)
	check(response.acceleration == Vector2.ZERO and response.impulse == Vector2.ZERO, "resume recalibrates")
	response = motion.sample(Vector3.ZERO, Vector3.ZERO, 1.0 / 60)
	check(not motion.available and response.acceleration == Vector2.ZERO, "unsupported device gracefully degrades")
	world.set_paused(false)
	world.select(fan.uid)
	app.open_editor()
	check(not world.paused, "editing keeps simulation running")
	app._notification(Node.NOTIFICATION_APPLICATION_PAUSED)
	check(world.paused, "background pauses live editor")
	app._notification(Node.NOTIFICATION_APPLICATION_RESUMED)
	check(not world.paused, "foreground restores live editor playback")
	app.close_editor(true)
	# Same wind, different mass: test physical result, not only a UI number.
	world.clear()
	world.set_paused(true)
	var light = world.spawn("ball", Vector2(150, 430), 0, {"mass": 1.0})
	var heavy = world.spawn("ball", Vector2(300, 430), 0, {"mass": 3.0})
	world.spawn("fan", Vector2(150, 510), 0, {"strength": 1250.0})
	world.spawn("fan", Vector2(300, 510), 0, {"strength": 1250.0})
	await ticks(3)
	world.set_paused(false)
	await ticks(12)
	check(light.linear_velocity.y < heavy.linear_velocity.y - 30, "heavier ball is physically harder to lift in identical wind")
	world.set_paused(true)
	world.select(light.uid)
	app.open_editor()
	await ticks(2)
	var handle := Vector2(app.hud.size.x / 2, app.hud.sheet_rect.position.y + 8)
	app.hud.pointer_down(handle, 0)
	app.hud.pointer_move(handle + Vector2(0, 60))
	app.hud.pointer_up(handle + Vector2(0, 60))
	check(app.modal == "", "swipe handle down closes sheet")
	var light_id: int = light.uid
	for height in [800, 1000]:
		root.size = Vector2i(450, height)
		await ticks(4)
		world.select(light_id)
		app.open_editor()
		await ticks(3)
		check(app.world_to_screen(world.bounds.end).y < app.hud.sheet_rect.position.y, "sheet keeps world visible at height " + str(height))
		check(app.world_to_screen(world.bounds.position).y >= app.hud.top + 72, "top is visible at height " + str(height))
		app.close_editor(true)
	var result := {"checks": checks, "failures": failures}
	var file := FileAccess.open("res://tests/revision-results.json", FileAccess.WRITE)
	file.store_string(JSON.stringify(result, "\t"))
	print(JSON.stringify(result))
	quit(0 if failures.is_empty() else 1)

